name: Custom branch CI

on:
  workflow_dispatch:
    inputs:
      LogLevel:
        description: 'Logging level for tests'
        required: true
        default: 'INFO'
      TestTag:
        description: 'Provided tag for execution'
        required: true
        default: 'Smoke'
      TestsToRun:
        description: 'Provided file name (e.g. tests/100cart_operations.robot'
        required: true
        default: 'tests'

jobs:
    Run-Custom-Test:
      runs-on: windows-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - uses: actions/cache@v2
          id: cache
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

        - name: Install pip dependencies
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Test
          run: python -m robot --outputdir reports --loglevel ${{github.event.inputs.LogLevel}} -i ${{github.event.inputs.TestTag}} ${{github.event.inputs.TestToRun}}

        - name: Publish test results
          if: always()
          uses: actions/upload-artifact@v2
          with:
            name: robot-test-results
            path: reports

        - name: Clean up repository
          if: always()
          shell: cmd
          run: if exist reports rmdir /Q /S reports