name: Alza Smoke test CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    Run-Test:
      runs-on: windows-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - uses: actions/cache@v2
          id: cache
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

        - name: Set resolution
          shell: cmd
          run: |
            dir "c:\"
            dir "c:\Program Files"
            dir "c:\Program Files\VMware"
            dir "c:\Program Files\VMware\VMware Tools"
            "c:\Program Files\VMware\VMware Tools\VMwareResolutionSet.exe" 0 1 , 0 0 1920 1080

        - name: Install pip dependencies
          if: always()
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Test
          if: always()
          run: python -m robot --outputdir reports -i Smoke tests

        - name: Publish test results
          if: always()
          uses: actions/upload-artifact@v2
          with:
            name: robot-test-results
            path: reports

        - name: Clean up repository
          if: always()
          shell: cmd
          run: if exist reports rmdir /Q /S reports
